theme: jekyll-theme-minimal
title: Mac Insights
description: Cogito ad infinitum
google_analytics: G-LTYEWLW89T
lang: en-CA

defaults:
  - scope:
      type: posts
    values:
      category: output
      image: /assets/images/logo.png
      permalink: /:categories/:year/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

github:
  is_project_page: false
  is_user_page: true

url: "https://ericfromcanada.github.io"
author: Eric Knibbe
social:
  links:
    - https://github.com/EricFromCanada
    - https://techhub.social/@EricFromCanada

readme_index:
  remove_originals: true

optional_front_matter:
  remove_originals: true
