theme: jekyll-theme-minimal
title: Mac Insights
description: Cogito ad infinitum
google_analytics: UA-972445-5
lang: en-CA

defaults:
  - scope:
      type: posts
    values:
      category: output
      permalink: /:categories/:year/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://ericfromcanada.github.io"
author: Eric Knibbe
social:
  links:
    - https://twitter.com/EricFromCanada
    - https://github.com/EricFromCanada
    - https://bitbucket.org/EricFromCanada
